spring:
  application:
    name: deliciasbatch
#  main:
    #banner-mode: off
    #allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_dev
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #format_sql: true
        jdbc:
          time_zone: UTC

delicias:
  tasks:
    cron: "0/5 * * * * *" # Cada 5s
  supabase:
    domain: 'http://192.168.101.100:8000'
    url: 'https://dooexrpqhljvevkhqbjr.supabase.co'
    key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvb2V4cnBxaGxqdmV2a2hxYmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MjI5MTEsImV4cCI6MjA3NzM5ODkxMX0.fhAKkxbiyf2ElTtHHCS75swvgVG5S1FlIb1eLishg-Y'
    bucket: 'delicias'
    logo: ${delicias.supabase.domain}/storage/v1/object/public/delicias/dl.png
  mapbox:
    token: 'sk.eyJ1IjoianVhbmpvc2VobSIsImEiOiJjbWgzdnhuZG0xaWh3dGNwcnVsM2E0cHRmIn0.-i_ngfFpCSOEXsl3duqHhg'